version: '3.8'

services:
  bff:
    container_name: demo-bff
    image: app/golang:latest
    build:
      context: .
      dockerfile: docker/golang/Dockerfile
    environment:
      - APM_NEWRELIC_LICENSE_KEY
    ports:
      - '4000:4000'
    networks:
      - app_subnet
    volumes:
      - golang_mod_cache:/go/pkg/mod
      - .:/app/api:rw
    working_dir: /app/api
    init: true
    command: ['go', 'run', 'bff/main.go']

  front:
    build:
      context: .
      dockerfile: docker/react/Dockerfile
    ports:
      - "3000:80"
    networks:
      - app_subnet

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - bff
    networks:
      - app_subnet

volumes:
  golang_mod_cache:

networks:
  app_subnet:
